### ISSUE TITLE
Remove "logger" as forced label on Github Issues

### ISSUE THREAD

**Issue by Taucher2003** [Taucher2003/Appenders#43]
In the [Github Issue Appender](https://github.com/Taucher2003/Appenders/blob/development/core/src/main/java/com/github/taucher2003/appenders/core/github/IssueAppender.java#L36) there is the label "logger" always added to the label list. This should be removed so the label is not forced anymore and optional

**Comment by soumyajitsamanta** [comment]
Added PR 44 (https://github.com/Taucher2003/Appenders/pull/44). Removed always addition of label "loggers".
