### ISSUE TITLE
Broken formatting

### ISSUE THREAD

**Issue by Taucher2003** [Taucher2003/Appenders#65]
# Bug Report

## Preconditions

- [x] I have checked for issues with similar reports
- [x] I have updated to the latest version
- [x] I have checked for open PRs with bug fixes

## Problem

![image](https://user-images.githubusercontent.com/39954661/133482779-f37e46a5-ae5e-4b3f-ba7c-1ed30ead4dc2.png)

Formatting is broken, needs to be fixed in the `utils` module in the [`Utilities`](https://github.com/Taucher2003/Appenders/blob/development/utils/src/main/java/com/github/taucher2003/appenders/utils/Utilities.java#L75) class

**Comment by stongia** [comment]
Hi, I like to pick this up can you please share more details on the issue.

**Comment by Taucher2003** [comment]
> Hi, I like to pick this up can you please share more details on the issue.

I thought the screenshot would be obvious. There is a newline missing after the `... x more`. I also linked to the class, which is the reason for that. Just click on the `Utilities` link in the description and you will get to the problematic line
